apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arch-homework.fullname" . }}-nginx
  labels:
    {{- include "arch-homework.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  {{- if not .Values.nginx.autoscaling.enabled }}
  replicas: {{ .Values.nginx.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arch-homework.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arch-homework.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ include "arch-homework.fullname" . }}-nginx
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: {{ template "arch-homework.fullname" . }}-claim
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arch-homework.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: pvc-volume
              mountPath: {{ .Values.workdir }}
          env:
            {{- toYaml .Values.nginx.envs | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            periodSeconds: 15
            failureThreshold: 5
            httpGet:
              path: {{ .Values.nginx.livenessProbe.path }}
              port: http
          readinessProbe:
            periodSeconds: 15
            failureThreshold: 5
            httpGet:
              path: {{ .Values.nginx.readinessProbe.path }}
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}