apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arch-homework.fullname" . }}-phpfpm-secret
type: Opaque
data:
  DB_USERNAME: {{ "postgres" | b64enc }}
  DB_PASSWORD: {{ "password" | b64enc }}
  DB_DATABASE: {{ "postgres" | b64enc }}
  REDIS_PASSWORD: {{ "password" | b64enc }}
  DB_PORT: {{ "5432" | b64enc }}
  APP_KEY: gH16p6kl8n6Uz61Z0oNcrtCaHWV7823Gg8sCjunvjwI=
