apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arch-homework.fullname" . }}-phpfpm
  labels:
    {{- include "arch-homework.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  {{- if not .Values.phpfpm.autoscaling.enabled }}
  replicas: {{ .Values.phpfpm.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arch-homework.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arch-homework.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: {{ template "arch-homework.fullname" . }}-claim
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arch-homework.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-db-ready
          image: postgres:9.6.5
          command: [ 'sh', '-c', 'until pg_isready -h $ARCH_HOMEWORK_POSTGRESQL_SERVICE_HOST -p 5432; do echo waiting for database; sleep 20; done;' ]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.phpfpm.image.repository }}:{{ .Values.phpfpm.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.phpfpm.image.pullPolicy }}
          volumeMounts:
            - name: pvc-volume
              mountPath: {{ .Values.workdir }}
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "cp -r /src/* {{ .Values.workdir }} && cd {{ .Values.workdir }} && php artisan config:cache && php artisan migrate --force" ]
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-secret
                  key: APP_KEY
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-secret
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-secret
                  key: DB_DATABASE
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-secret
                  key: DB_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-secret
                  key: REDIS_PASSWORD
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-configmap
                  key: APP_ENV
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-configmap
                  key: APP_DEBUG
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "arch-homework.fullname" . }}-phpfpm-configmap
                  key: APP_URL
          ports:
            - name: phpfpm
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: phpfpm
          readinessProbe:
            tcpSocket:
              port: phpfpm
          resources:
            {{- toYaml .Values.phpfpm.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}