kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "arch-homework.fullname" . }}
  labels: {{- include "arch-homework.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.storage | quote }}
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: {{ template "arch-homework.fullname" . }}
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "arch-homework.fullname" . }}-claim
  namespace: {{ .Release.Namespace }}
  labels: {{- include "arch-homework.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    checksum/values: {{ toYaml .Values | sha256sum | trunc 20 | quote }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage | quote }}