{
 "title": "Arch homework",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(requests_app_request_count[1m]))",
     "legendFormat": "RPS {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency by endpoints (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(requests_app_request_latency_seconds_bucket[1m]))\n) * 10000",
     "legendFormat": "{{ exported_endpoint }}, ms"
    }
   ]
  },
  {
   "title": "Latency by endpoints (0.5)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(requests_app_request_latency_seconds_bucket[1m]))\n) * 10000",
     "legendFormat": "{{ exported_endpoint }}, ms"
    }
   ]
  },
  {
   "title": "Latency by endpoints (0.95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(requests_app_request_latency_seconds_bucket[1m]))\n) * 10000",
     "legendFormat": "{{ exported_endpoint }}, ms"
    }
   ]
  },
  {
   "title": "Latency by endpoints (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(requests_app_request_latency_seconds_bucket[1m]))\n) * 10000",
     "legendFormat": "{{ exported_endpoint }}, ms"
    }
   ]
  }
 ]
}