apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-arch-homework-dashboard
  labels:
    grafana_dashboard: '1'
data:
  arch_homework_dashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [ ],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 14,
      "iteration": 1646166282824,
      "links": [ ],
      "liveNow": false,
      "panels": [
        {
          "aliasColors": { },
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": {
            "uid": "$datasource"
          },
          "fill": 10,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 24,
            "x": 0,
            "y": 1
          },
          "hiddenSeries": false,
          "id": 1,
          "interval": "1m",
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "rightSide": true,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 0,
          "links": [ ],
          "nullPointMode": "null as zero",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "8.3.6",
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "requests",
              "color": "#F2495C",
              "fill": 0,
              "hideTooltip": true,
              "legend": true,
              "linewidth": 2,
              "stack": false
            },
            {
              "alias": "limits",
              "color": "#FF9830",
              "fill": 0,
              "hideTooltip": true,
              "legend": true,
              "linewidth": 2,
              "stack": false
            }
          ],
          "spaceLength": 10,
          "stack": true,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\", cluster=\"$cluster\"}) by (container)",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "{{container}}",
              "refId": "A",
              "step": 10
            },
            {
              "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "requests",
              "refId": "B",
              "step": 10
            },
            {
              "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "limits",
              "refId": "C",
              "step": 10
            }
          ],
          "thresholds": [ ],
          "timeRegions": [ ],
          "title": "CPU Usage",
          "tooltip": {
            "shared": false,
            "sort": 2,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "show": true,
            "values": [ ]
          },
          "yaxes": [
            {
              "format": "short",
              "logBase": 1,
              "min": 0,
              "show": true
            },
            {
              "format": "short",
              "logBase": 1,
              "show": false
            }
          ],
          "yaxis": {
            "align": false
          }
        },
        {
          "aliasColors": { },
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": {
            "uid": "$datasource"
          },
          "fill": 10,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 24,
            "x": 0,
            "y": 25
          },
          "hiddenSeries": false,
          "id": 4,
          "interval": "1m",
          "legend": {
            "alignAsTable": true,
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "rightSide": true,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 0,
          "links": [ ],
          "nullPointMode": "null as zero",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "8.3.6",
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "requests",
              "color": "#F2495C",
              "dashes": true,
              "fill": 0,
              "hideTooltip": true,
              "legend": true,
              "linewidth": 2,
              "stack": false
            },
            {
              "alias": "limits",
              "color": "#FF9830",
              "dashes": true,
              "fill": 0,
              "hideTooltip": true,
              "legend": true,
              "linewidth": 2,
              "stack": false
            }
          ],
          "spaceLength": 10,
          "stack": true,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "{{container}}",
              "refId": "A",
              "step": 10
            },
            {
              "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "requests",
              "refId": "B",
              "step": 10
            },
            {
              "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", resource=\"memory\"}\n)\n",
              "format": "time_series",
              "intervalFactor": 2,
              "legendFormat": "limits",
              "refId": "C",
              "step": 10
            }
          ],
          "thresholds": [ ],
          "timeRegions": [ ],
          "title": "Memory Usage",
          "tooltip": {
            "shared": false,
            "sort": 2,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "mode": "time",
            "show": true,
            "values": [ ]
          },
          "yaxes": [
            {
              "format": "bytes",
              "logBase": 1,
              "min": 0,
              "show": true
            },
            {
              "format": "short",
              "logBase": 1,
              "show": false
            }
          ],
          "yaxis": {
            "align": false
          }
        }
      ],
      "refresh": "10s",
      "schemaVersion": 34,
      "style": "dark",
      "tags": [ ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "default",
              "value": "default"
            },
            "hide": 0,
            "includeAll": false,
            "label": "Data Source",
            "multi": false,
            "name": "datasource",
            "options": [ ],
            "query": "prometheus",
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "type": "datasource"
          },
          {
            "current": {
              "isNone": true,
              "selected": false,
              "text": "None",
              "value": ""
            },
            "datasource": {
              "type": "prometheus",
              "uid": "$datasource"
            },
            "definition": "",
            "hide": 2,
            "includeAll": false,
            "multi": false,
            "name": "cluster",
            "options": [ ],
            "query": {
              "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)",
              "refId": "Prometheus-cluster-Variable-Query"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          },
          {
            "current": {
              "selected": false,
              "text": "default",
              "value": "default"
            },
            "datasource": {
              "type": "prometheus",
              "uid": "$datasource"
            },
            "definition": "",
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "namespace",
            "options": [ ],
            "query": {
              "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)",
              "refId": "Prometheus-namespace-Variable-Query"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          },
          {
            "current": {
              "selected": false,
              "text": "arch-homework-nginx-655d77c9c9-c4tf5",
              "value": "arch-homework-nginx-655d77c9c9-c4tf5"
            },
            "datasource": {
              "type": "prometheus",
              "uid": "$datasource"
            },
            "definition": "",
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "pod",
            "options": [ ],
            "query": {
              "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)",
              "refId": "Prometheus-pod-Variable-Query"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 1,
            "tagValuesQuery": "",
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ],
        "time_options": [
          "5m",
          "15m",
          "1h",
          "6h",
          "12h",
          "24h",
          "2d",
          "7d",
          "30d"
        ]
      },
      "timezone": "utc",
      "title": "Kubernetes Pod",
      "uid": "6581e46e4e5c7ba40a07646395ef7b23",
      "version": 1,
      "weekStart": ""
    }
