apiVersion: v1
kind: Service
metadata:
  name: {{ include "arch-homework.fullname" . }}-nginx
  labels:
    {{- include "arch-homework.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arch-homework.selectorLabels" . | nindent 4 }}
