kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "arch-homework.fullname" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arch-homework.labels" . | nindent 4 }}
    component: nginx
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;

        sendfile       on;
        tcp_nopush     on;
        resolver_timeout 10s;
        server_tokens off;
        keepalive_timeout 60;
        reset_timedout_connection on;
        client_body_timeout 10;
        send_timeout 2;
        proxy_buffering off;

        gzip on;
        gzip_comp_level 9;
        gzip_disable "msie6";
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript image/svg+xml;

        root {{ .Values.nginx.workdir_conf }};
        server_name _;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }

        location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass {{ include "arch-homework.fullname" . }}-phpfpm:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          fastcgi_param REQUEST_METHOD $request_method;
        }
      }
    }