apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arch-homework.fullname" . }}-phpfpm
  labels:
    {{- include "arch-homework.labels" . | nindent 4 }}
spec:
  {{- if not .Values.phpfpm.autoscaling.enabled }}
  replicas: {{ .Values.phpfpm.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arch-homework.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "arch-homework.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: {{ template "arch-homework.fullname" . }}-claim
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "arch-homework.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.phpfpm.image.repository }}:{{ .Values.phpfpm.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.phpfpm.image.pullPolicy }}
          volumeMounts:
            - name: pvc-volume
              mountPath: {{ .Values.workdir }}
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "cp -r /src/* {{ .Values.workdir }}" ]
          env:
            {{- toYaml .Values.phpfpm.envs | nindent 12}}
          ports:
            - name: phpfpm
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: phpfpm
          readinessProbe:
            tcpSocket:
              port: phpfpm
          resources:
            {{- toYaml .Values.phpfpm.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}